# Generated by Django 5.2.3 on 2025-08-08 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='progress',
            name='progress_percentage',
            field=models.FloatField(default=0),
        ),
    ]
