# Generated by Django 5.2.3 on 2025-08-09 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0002_progress_notes_progress_progress_percentage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progress',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='progress',
            name='progress_percentage',
        ),
    ]
