# Generated by Django 5.2.3 on 2025-08-17 12:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_alter_category_options_alter_course_options_and_more'),
        ('progress', '0003_remove_progress_notes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='progress',
            options={'ordering': ['-last_updated']},
        ),
        migrations.AddField(
            model_name='progress',
            name='completed_assignments',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='progress',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterUniqueTogether(
            name='progress',
            unique_together={('kid', 'course')},
        ),
    ]
