# Generated by Django 5.2.3 on 2025-08-17 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0004_alter_progress_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='total_assignments',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='progress',
            name='total_lessons',
            field=models.IntegerField(default=0),
        ),
    ]
