# Generated by Django 5.2.3 on 2025-08-17 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("progress", "0005_progress_total_assignments_progress_total_lessons"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="progress",
            name="total_assignments",
        ),
        migrations.RemoveField(
            model_name="progress",
            name="total_lessons",
        ),
    ]
