# Generated by Django 5.2.3 on 2025-08-18 19:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0010_merge_20250818_1946"),
        ("progress", "0006_remove_progress_total_assignments_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="progress",
            name="date",
        ),
        migrations.RemoveField(
            model_name="progress",
            name="performance_notes",
        ),
        migrations.AddField(
            model_name="progress",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="progress",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="progress_entries",
                to="courses.course",
            ),
        ),
        migrations.AlterField(
            model_name="progress",
            name="kid",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="course_progress",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="progress",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children_progress",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
