# Generated by Django 5.2.3 on 2025-08-19 09:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("progress", "0007_remove_progress_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="progress",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
