# Generated by Django 5.2.3 on 2025-08-15 16:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_user_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("Kid", "Kid"), ("Parent", "Parent"), ("Admin", "Admin")],
                default="Kid",
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="KidParentRelation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kid",
                    models.ForeignKey(
                        limit_choices_to={"role": "Kid"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parent_relations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        limit_choices_to={"role": "Parent"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children_relations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
