# Generated by Django 5.2.3 on 2025-08-03 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Kid', 'Kid'), ('Parent', 'Parent'), ('Admin', 'Admin')], default='kid', max_length=10),
        ),
    ]
