# Generated by Django 5.2.3 on 2025-08-19 22:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_user_bio_remove_user_profile_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('bio', models.TextField(blank=True, max_length=300)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('favorite_language', models.CharField(blank=True, choices=[('Python', 'Python'), ('JavaScript', 'JavaScript'), ('Scratch', 'Scratch'), ('HTML/CSS', 'HTML/CSS')], max_length=50)),
                ('skill_level', models.CharField(choices=[('Beginner', 'مبتدئ'), ('Intermediate', 'متوسط'), ('Advanced', 'متقدم')], default='Beginner', max_length=20)),
                ('points', models.IntegerField(default=0)),
                ('courses_completed', models.IntegerField(default=0)),
                ('badges', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
