# Generated by Django 5.2.3 on 2025-08-05 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name="lesson",
        #     name="course",
        # ),
        # migrations.DeleteModel(
        #     name="Assignment",
        # ),
        # migrations.DeleteModel(
        #     name="Lesson",
        # ),
    ]
