# Generated by Django 5.2.3 on 2025-08-16 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_enrollment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('bio', models.TextField(blank=True, help_text='A brief bio about the instructor', null=True)),
                ('specialization', models.CharField(blank=True, help_text='Specialization', max_length=200, null=True)),
                ('years_of_experience', models.PositiveIntegerField(default=0, help_text='Years of experience')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='instructors/')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='instructors',
            field=models.ManyToManyField(blank=True, help_text='Instructors responsible for this course', related_name='courses', to='courses.instructor'),
        ),
    ]
