# Generated by Django 5.2.3 on 2025-08-17 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0007_alter_category_options_alter_course_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="total_assignments",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="course",
            name="total_lessons",
            field=models.IntegerField(default=0),
        ),
    ]
