# Generated by Django 5.2.3 on 2025-08-18 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0008_course_total_assignments_course_total_lessons"),
        ("courses", "0009_alter_instructor_profile_image"),
    ]

    operations = []
