# Generated by Django 5.2.3 on 2025-08-11 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("assignments", "0002_submission"),
    ]

    operations = [
        migrations.RenameField(
            model_name="assignment",
            old_name="answer",
            new_name="model_answer",
        ),
        migrations.RemoveField(
            model_name="assignment",
            name="kid",
        ),
        migrations.RemoveField(
            model_name="assignment",
            name="submitted",
        ),
    ]
