<<<<<<< HEAD
# Generated by Django 5.2.3 on 2025-08-05 20:34
=======

>>>>>>> 5fa0b64709397a13d35bac279832eee4ad3d2e1f

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
        ("courses", "0001_initial"),
=======
        ("courses", "0002_remove_lesson_course_delete_assignment_delete_lesson"),
        ('courses', '0001_initial'),
>>>>>>> 5fa0b64709397a13d35bac279832eee4ad3d2e1f
    ]

    operations = [
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField()),
                ("video_url", models.URLField(blank=True, null=True)),
                ("order", models.PositiveIntegerField()),
                (
                    "course",
                    models.ForeignKey(
<<<<<<< HEAD
                        on_delete=django.db.models.deletion.CASCADE, to="courses.course"
                    ),
                ),
=======
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lessons",
                        to="courses.course",)),
>>>>>>> 5fa0b64709397a13d35bac279832eee4ad3d2e1f
            ],
        ),
    ]