# Generated by Django 5.2.3 on 2025-08-16 15:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_enrollment'),
        ('lessons', '0006_lesson_is_completed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['course', 'order']},
        ),
        migrations.AddField(
            model_name='lesson',
            name='instructors',
            field=models.ManyToManyField(blank=True, help_text='The instructors responsible for this lesson', limit_choices_to={'role': 'Instructor'}, related_name='lessons_taught', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together={('course', 'order')},
        ),
    ]
