# Generated by Django 5.2.3 on 2025-08-16 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0007_add_instructors_relation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='instructors',
        ),
    ]
